//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 测试EF读写分离01
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Ticket
    {
        public int TicketId { get; set; }
        public int EnterpriseId { get; set; }
        public int ScenicId { get; set; }
        public int TypeId { get; set; }
        public string TicketName { get; set; }
        public System.DateTime ExpiryDateStart { get; set; }
        public System.DateTime ExpiryDateEnd { get; set; }
        public Nullable<decimal> MarkPrice { get; set; }
        public decimal SalePrice { get; set; }
        public Nullable<decimal> SettlementPrice { get; set; }
        public Nullable<int> StockCount { get; set; }
        public Nullable<int> SellCount { get; set; }
        public int CheckWay { get; set; }
        public Nullable<int> DelayCheck { get; set; }
        public int OrderId { get; set; }
        public int DataStatus { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int CreateUserId { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public Nullable<int> LastUpdateUserId { get; set; }
        public int TicketSource { get; set; }
        public int RuleId { get; set; }
        public Nullable<decimal> LossFee { get; set; }
        public string Code { get; set; }
        public int MinOQ { get; set; }
        public int MaxOQ { get; set; }
        public string ShelvesChannel { get; set; }
    }
}
