//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 测试EF读写分离01
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Order
    {
        public int OrderId { get; set; }
        public string OrderNo { get; set; }
        public int EnterpriseId { get; set; }
        public int ScenicId { get; set; }
        public int TicketSource { get; set; }
        public int PayType { get; set; }
        public string PayAccount { get; set; }
        public string PayTradeNo { get; set; }
        public int SellerId { get; set; }
        public string TicketName { get; set; }
        public int BookCount { get; set; }
        public decimal TotalAmount { get; set; }
        public string Linkman { get; set; }
        public string Mobile { get; set; }
        public int OrderStatus { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<System.DateTime> PayTime { get; set; }
        public System.DateTime ValidityDateStart { get; set; }
        public System.DateTime ValidityDateEnd { get; set; }
        public Nullable<System.DateTime> CancelTime { get; set; }
        public Nullable<int> UsedQuantity { get; set; }
        public string Remark { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> IDType { get; set; }
        public string IDCard { get; set; }
        public int CreateUserId { get; set; }
        public Nullable<int> BuyUserId { get; set; }
        public Nullable<int> Source { get; set; }
        public string OTAOrderNo { get; set; }
        public Nullable<int> OTABusinessId { get; set; }
        public bool CanRefund { get; set; }
        public Nullable<System.DateTime> CanRefundTime { get; set; }
        public bool CanModify { get; set; }
        public Nullable<System.DateTime> CanModifyTime { get; set; }
        public string ReceiverName { get; set; }
        public int OrderType { get; set; }
        public int GroupWay { get; set; }
        public string OTABusinessName { get; set; }
    }
}
